# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2938535866f472e7494fba0ca310135d604bf341a21780712b58aafda71e98314313592e4c75070f9a94782c8015367b70b79b8c1d4073a4661840fee68e1324

test:
  secret_key_base: 10a35b10a5a2af7a78e464256c730070649de4023492aa32b7f7f0e58aa9e23151bc1e6a5dbc661765f179498a4c5b57da6721b963ade68f06ba09f8a0236591

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
